services:
  flags-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flags-api
    restart: always  
    networks:
      - traefik-proxy
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-proxy"
        - "traefik.http.routers.flags-api.entrypoints=http"
        - "traefik.http.routers.flags-api.rule=Host(`flags-api.cloud.local`)"
        - "traefik.http.middlewares.flags-api-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.flags-api.middlewares=flags-api-https-redirect"
        - "traefik.http.routers.flags-api-secure.entrypoints=https"
        - "traefik.http.routers.flags-api-secure.rule=Host(`flags-api.cloud.local`)"
        - "traefik.http.routers.flags-api-secure.tls=true"
        #- "traefik.http.routers.flags-api-secure.tls.certresolver=http"
        - "traefik.http.services.flags-api-secure.loadbalancer.server.port=3000"

networks:
  traefik-proxy:
    external: true